site_name: LSL.ServiceCollections
site_url: https://alunacjones.github.io/LSL.ServiceCollections/
repo_url: https://github.com/alunacjones/LSL.ServiceCollections
extra_css:
  - css/tryIt.css
extra_javascript:
  - javascript/tryIt.js
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - tables
  - attr_list
theme: 
  name: material
  features:
    - content.code.copy  
    - navigation.expand